spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
spring:
  profiles: dev
  application:
    name: microservice-dept
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
mybatis: 
  type-aliases-package: org.cloris.domain
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
eureka:
  instance:
    instance-id: microservice-dept-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/
info:
  app.name: department-service
  author: cloris
  build.artifactId: ${project.artifactId}
